### ISSUE TITLE
Setting target time generates error

### ISSUE THREAD

**Issue by dmsims** [dan-r/HomeAssistant-Ohme#61]
**What happened?**
Change target time generates an onscreen error which appears very briefly bottom right see screenshot
![Screenshot 2024-02-15 192216](https://github.com/dan-r/HomeAssistant-Ohme/assets/4712953/3789ba6e-f824-491f-b4a6-d251e20ea094)

**To Reproduce**
type any value in box nand move away

**Expected behavior**

**Log Output**
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 14 February 2024 at 20:55:26 (9 occurrences)
Last logged: 19:14:55

[139865960401728] name 'current' is not defined
[139866127864256] name 'current' is not defined
[139866369697088] name 'current' is not defined
[139865774974656] name 'current' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/time/__init__.py", line 41, in _async_set_value
    return await entity.async_set_value(service_call.data[ATTR_TIME])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/time.py", line 72, in async_set_value
    await self._client.async_apply_session_rule(target_time=(int(value.hour), int(value.minute)))
  File "/config/custom_components/ohme/api_client.py", line 222, in async_apply_session_rule
    target_ts = int(time_next_occurs(
                    ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/utils.py", line 177, in time_next_occurs
    target = current.replace(hour=hour, minute=minute, second=0, microsecond=0)
             ^^^^^^^
NameError: name 'current' is not defined

**Home Assistant Version**
Core
2024.2.1
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.1

**Integration Version**
0.7.0

**Additional context**

**Comment by dan-r** [comment]
Looks like a line went missing in that file. Mind trying v0.7.1-beta.1?

**Comment by dmsims** [comment]
No error mesages with this release , thank you

**Comment by dan-r** [comment]
Released as stable v0.7.1
