### ISSUE TITLE
Fail to load after reboot 

### ISSUE THREAD

**Issue by neil192** [dan-r/HomeAssistant-Ohme#63]
**What happened?**
After a reboot the ohme addon does not load

**To Reproduce**
Restart server

**Expected behavior**
Addon automatically loads

**Log Output**
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 09:11:51 (1 occurrences)
Last logged: 09:11:51

Error setting up entry Ohme Charger for ohme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/__init__.py", line 38, in async_setup_entry
    await async_setup_dependencies(hass, entry)
  File "/config/custom_components/ohme/__init__.py", line 23, in async_setup_dependencies
    await client.async_create_session()
  File "/config/custom_components/ohme/api_client.py", line 54, in async_create_session
    async with self._auth_session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

**Home Assistant Version**
Beta 6.2

**Integration Version**
Find this from HACS.

**Additional context**

**Comment by dan-r** [comment]
Could you please update to v0.7.1 and see if that helps?

**Comment by neil192** [comment]
Sorry still have the same problem

Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 09:30:15 (1 occurrences)
Last logged: 09:30:15

Error setting up entry Ohme Charger for ohme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444,
in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ohme/__init__.py", line 38, in
async_setup_entry
    await async_setup_dependencies(hass, entry)
  File "/config/custom_components/ohme/__init__.py", line 23, in
async_setup_dependencies
    await client.async_create_session()
  File "/config/custom_components/ohme/api_client.py", line 54, in
async_create_session
    async with self._auth_session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line
1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line
504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line
735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

**Comment by dan-r** [comment]
Odd - have you changed your Ohme password recently? Looks to be either wrong credentials or a network issue.

**Comment by neil192** [comment]
Not recently, if I select reload it works fine

**Comment by dan-r** [comment]
That's very odd - what version of home assistant are you running?

**Comment by neil192** [comment]
2024.2.1

**Comment by davelegg83** [comment]
Hi Dan,
I seem to be having the same issue. After every restart of HA, I need to go in and reload this. On the latest version of HA.
When I was setting this up, I did forget my password, so had to do a reset to get this running on HA, and when I charged my car next had to log out of the app and back in with the new password if that helps.

PS - Love this and the Leaf app! Thank you so much for creating them.

**Comment by dan-r** [comment]
@davelegg83 can I just confirm you are using the latest version of both Home Assistant and this integration? I'm not seeing this behaviour currently.

**Comment by dan-r** [comment]
@neil192 are you still seeing this issue?

**Comment by davelegg83** [comment]
Hi @dan-r ,
Can confirm i'm on the latest HA release and also latest version of this intergration.

**Comment by neil192** [comment]
Screen shots attached

**Comment by graemejross** [comment]
Hi @dan-r 

I get the same issue.  Fails to load after a reboot but loads correctly when I reload.  Running version v0.7.1 of the Ohme integration and HA version 2024.2.5.

Thanks, Graeme

**Comment by dan-r** [comment]
I tend to stick to the monthly/stable releases (so 2024.2.0 at the moment), but will try the versions you three are using. I'm away for a couple of days but will get a chance to look at it on Monday. 

Dan

**Comment by dan-r** [comment]
I've tried out v0.7.1 with Home Assistant 2024.2.5 and can't seem to replicate the issue.

Does anyone experiencing this issue see anything odd going on with other integrations? 

Might be worth enabling debug logs and either putting them in here or emailing to me if problems persist.

Dan

**Comment by neil192** [comment]
This is what I get in the logs


2024-03-04 14:26:07.164 ERROR (MainThread) [homeassistant.config_entries]
Error setting up entry Ohme Charger for ohme
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in
async_setup

result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ohme/__init__.py", line 38, in
async_setup_entry
await async_setup_dependencies(hass, entry)
File "/config/custom_components/ohme/__init__.py", line 23, in
async_setup_dependencies
await client.async_create_session()
File "/config/custom_components/ohme/api_client.py", line 54, in
async_create_session
async with self._auth_session.post(
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line
1194, in __aenter__
self._resp = await self._coro
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504,
in _request
with timer:
File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line
735, in __exit__
raise asyncio.TimeoutError from None
TimeoutError

**Comment by dan-r** [comment]
Just to keep you updated, I'm still looking into a fix

**Comment by neil192** [comment]
Since the last update, I have restarted a number of times and I haven't
seen the issue 😀😀😀

**Comment by dan-r** [comment]
Good to hear - I'll close this issue for now but if you see the behaviour again please re-open it.

Dan
